# Generated by Django 2.2 on 2019-11-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191108_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='timezone.now', verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='updated',
            field=models.DateTimeField(auto_now=True, default='timezone.now', verbose_name='Fecha de edición'),
            preserve_default=False,
        ),
    ]
